export const SETTINGS = {
  accessories: [
    'None',
    'Glasses',
    'Glasses 2',
    'Glasses 3',
    'Glasses 4',
    'Glasses 5',
    'Sunglasses',
    'Sunglasses 2',
    'Eyepatch',
  ],
  body:[
    'Blazer Black Tee',
    'Button Shirt 1',
    'Button Shirt 2',
    'Coffee',
    'Device',
    'Dress',
    'Explaining',
    'Gaming',
    'Fur Jacket',
    'Gym Shirt',
    'Hoodie',
    'Killer',
    'Macbook',
    'Paper',
    'Pointing Up',
    'Polka Dot Jacket',
    'Polo and Sweater',
    'Shirt and Coat',
    'Sporty Tee',
    'Striped Pocket Tee',
    'Striped Tee',
    'Tee 1',
    'Tee 2',
    'Turtleneck',
    'Whatever',
  ],
  face: [
    'Angry with Fang',
    'Awe',
    'Blank',
    'Calm',
    'Cheeky',
    'Concerned Fear',
    'Concerned',
    'Contempt',
    'Cute',
    'Cyclops',
    'Driven',
    'Eating Happy',
    'Explaining',
    'Eyes Closed',
    'Fear',
    'Hectic',
    'Loving Grin 1',
    'Loving Grin 2',
    'Monster',
    'Old',
    'Rage',
    'Serious',
    'Smile Big',
    'Smile LOL',
    'Smile Teeth Gap',
    'Smile',
    'Solemn',
    'Suspicious',
    'Tired',
    'Very Angry'
  ],
  facialHair: [
    'None',
    'Chin',
    'Full 2',
    'Full 3',
    'Full 4',
    'Full',
    'Goatee 1',
    'Goatee 2',
    'Moustache 1',
    'Moustache 2',
    'Moustache 3',
    'Moustache 4',
    'Moustache 5',
    'Moustache 6',
    'Moustache 7',
    'Moustache 8',
    'Moustache 9'
  ],
  head: [
    'Afro',
    'Bangs 2',
    'Bangs',
    'Bantu Knots',
    'Bear',
    'Buns',
    'Cornrows 2',
    'Cornrows',
    'Flat Top Long',
    'Flat Top',
    'Gray Bun',
    'Gray Medium',
    'Gray Short',
    'hat-beanie',
    'hat-hip',
    'Long Bangs',
    'Long',
    'Medium 1',
    'Medium 2',
    'Medium 3',
    'Medium Bangs 2',
    'Medium Bangs 3',
    'Medium Bangs',
    'Medium Straight',
    'Mohawk 2',
    'Mohawk',
    'No Hair 1',
    'No Hair 2',
    'No Hair 3',
    'Pomp',
    'Shaved 1',
    'Shaved 2',
    'Shaved 3',
    'Short 1',
    'Short 2',
    'Short 3',
    'Short 4',
    'Short 5',
    'Twists 2',
    'Twists'
  ],
  eyes: [
    'angry',
    'calm',
    'closed',
    'contempt',
    'driven',
    'eating',
    'fear',
    'loving',
    'old',
    'Smile Big',
    'smile',
    'Suspicious',
    'Tired',
  ],
  mouth: [
    'angry',
    'calm',
    'closed',
    'contempt',
    'driven',
    'eating',
    'fear',
    'loving',
    'old',
    'Smile Big',
    'smile',
    'Suspicious',
    'Tired',
  ],
  nose: [
    'angry',
    'calm',
    'closed',
    'contempt',
    'driven',
    'eating',
    'fear',
    'loving',
    'old',
    'Smile Big',
    'smile',
    'Suspicious',
    'Tired',
  ],
  eyebrows: [
    'angry',
    'calm',
    'closed',
    'contempt',
    'driven',
    'eating',
    'fear',
    'loving',
    'old',
    'Smile Big',
    'smile',
    'Suspicious',
    'Tired',
  ],
}
